import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import styled from "styled-components";

//GRIDRION THU NGHIEM
import Box from "../src/components/Box/Box";
import Grid from "../src/components/Grid/Grid";
import GridRuler from "../src/components/GridRuler/GridRuler";

// HUNTER import Grid from "../src/components/Layout/Grid";
import FullWidthSection from "../src/components/Layout/FullWidthSection";
import MaxWidthSection from "../src/components/Layout/MaxWidthSection";
import Row from "../src/components/Layout/Row";

import { relative } from "path";

const HunterHeader = styled(FullWidthSection)`
  padding: 4rem 1.5rem;
  background-color: lightcoral;
`;

// const Nav = styled(Row)`
//   a {
//     margin-right: 1rem;
//   }
// `;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <h2 className={styles.description}>
          Note our stock nextJS vercel uses a grid that we can later expound
          upon...
          {/* <code className={styles.code}>pages/index.js</code> */}
        </h2>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>

        {/*GI HUNTER
        Tutorial: Responsive CSS Grid System for React
        https://www.youtube.com/watch?v=sI1iC600FiQ&list=PL1o4UW0Tw5ZYwRczE2BU-Q58Gcm1zcZRn&index=51&t=156s
         */}

        {/* <Grid>
          <HunterHeader> */}
            {/* <Nav as="nav" sd={2} ed={12} sm={2} em={6} ss={2} se={6}>
          <a href="#">Home</a>
          <a href="#">About</a>
        </Nav> */}
          {/* </HunterHeader>
        </Grid> */}

        <h2 className={styles.description}>But Moving on With GRID HUNTER</h2>

      </main>


      <h2 className={styles.description}>GRIDIRON | THU NGHIEM</h2>
      <div className="gridThu" style={{background: 'lightgreen', margin: '16px', position: 'relative', height: '100vh'}}>

        {/* Change BOTH spacing props here for correct ruler spacing */}
        <GridRuler spacing="sm"></GridRuler>

        {/* GRID CONTAINER */}
          {/* OPTION justifyContent : Prop values  'flex-start' | 'center' | 'flex-end' | 'space-between'; */}
          {/* OPTION alignItems : Prop values  'flex-start' | 'center' | 'flex-end' |  */}
          {/* OPTION Spacing : Prop Options :  - sm, md or lg - ...wonder if we could create a prop for container size too? */}
        <Grid
          container
          spacing="sm"
          alignItems="center"
          style={{ height: "100%" }}>

          <Grid item xs={1} sm={6} md={4} lg={3}>
            <Box>Box 1</Box>
          </Grid>

          <Grid item xs={1} sm={6} md={4} lg={3}>
            <Box>Box 2</Box>
          </Grid>

          <Grid item xs={1} sm={6} md={4} lg={3}>
            <Box>Box 3</Box>
          </Grid>

          <Grid item xs={1} sm={6} md={4} lg={3}>
            <Box>Box 4</Box>
          </Grid>

        </Grid>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
